# Generated by Django 6.0.2 on 2026-06-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing_comment_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.TextField(default="NO DESCRIPTION"),
        ),
    ]
